### ISSUE TITLE
Ignoring network definitions

### ISSUE THREAD

**Issue by sebgoa** [skippbox/kompose#149]
Currently we ignore networks definition in services , but looks like we don't properly parse and ignore global networks definitions.

```
version: '2'

services:
...
networks:
  foobar:
  barfoo:
```

kompose seems to fail if these networks are defined. We need to successfully parse but give a warning.
