### ISSUE TITLE
convert file fail

### ISSUE THREAD

**Issue by wayarmy** [skippbox/kompose#47]
i've just use "kompose convert" from an docker-compose.yaml file to new file yml of k8s, but it went wrong, and show me the error: 
"ERRO[0000] Failed to unmarshall: Cannot unmarshal '30' of type int64 into a string value"

Is this new issue? Or i did wrong?

@ngtuna

**Comment by ngtuna** [comment]
@wayarmy Could you please upload your compose file ?

**Comment by wayarmy** [comment]
`redis:
  image: redis:latest
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"
static:
  image: wayarmy/jackfruit:0.1
  ports:
    - "80:8080"

jackfruit: &app_base
  image: wayarmy/jackfruit:0.1
  ports:
    - "8080"
  links: &app_links
    - redis:redis.local
    - elasticsearch:elasticsearch.local
    - static:static.local
  environment:
    RAILS_ENV: 'production'
    RAILS_SERVE_STATIC_FILES: 'true'
    UNICORN_PORT: '8080'
    UNICORN_PROCESSES: '2'
    UNICORN_TIMEOUT: '30'
    UNICORN_WORKING_DIR: '/home/rails/jackfruit/'
    UNICORN_PID: '/home/rails/jackfruit/shared/pids/unicorn.pid'
    UNICORN_ERR_LOG: '/home/rails/jackfruit/shared/log/unicorn.stderr.log'
    UNICORN_LOG: '/home/rails/jackfruit/shared/log/unicorn.stdout.log'`

something like this?? Is this OK?

**Comment by janetkuo** [comment]
This works for me:

With this test-compose.yml file
```yaml
redis:
  image: redis:latest
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"
static:
  image: wayarmy/jackfruit:0.1
  ports:
    - "80:8080"

jackfruit: &app_base
  image: wayarmy/jackfruit:0.1
  ports:
    - "8080"
  links: &app_links
    - redis:redis.local
    - elasticsearch:elasticsearch.local
    - static:static.local
  environment:
    RAILS_ENV: 'production'
    RAILS_SERVE_STATIC_FILES: 'true'
    UNICORN_PORT: '8080'
    UNICORN_PROCESSES: '2'
    UNICORN_TIMEOUT: '30'
    UNICORN_WORKING_DIR: '/home/rails/jackfruit/'
    UNICORN_PID: '/home/rails/jackfruit/shared/pids/unicorn.pid'
    UNICORN_ERR_LOG: '/home/rails/jackfruit/shared/log/unicorn.stderr.log'
    UNICORN_LOG: '/home/rails/jackfruit/shared/log/unicorn.stdout.log'
```

```console 
$ ../kompose convert -f test-compose.yml
file "jackfruit-svc.json" created
file "redis-svc.json" created
file "static-svc.json" created
file "elasticsearch-svc.json" created
file "redis-deployment.json" created
file "static-deployment.json" created
file "elasticsearch-deployment.json" created
file "jackfruit-deployment.json" created
```
