### ISSUE TITLE
docker-compose service with no ports is mapped to k8s svc with no ports

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#58]
When a docker-compose service is given with no ports, a corresponding k8s service is created with no port info, and this is wrong config, because port is required value.

`docker-compose.yml` file I used.
```yaml
$ cat docker-compose-no-ports.yml 
  mariadb:
    image: centos/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: etherpad
      MYSQL_DATABASE: etherpad
      MYSQL_PASSWORD: etherpad
      MYSQL_USER: etherpad
```

convert

```bash
$ ./kompose convert -f docker-compose-no-ports.yml -o output -y
file "output" created
$ cat output 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  ports: []
  selector:
    service: mariadb
status:
  loadBalancer: {}
---
[SNIP]
```

When this definition is fed to kubernetes it says:

```bash
$ kubectl create -f svc 
The Service "mariadb" is invalid.
spec.ports: Required value
```

Where `svc` is:
```bash
$ cat svc 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  ports: []
  selector:
    service: mariadb
status:
  loadBalancer: {}
```

IMO this should error out or should not create service, give warning loud and clear that service is not created, but still we can have `deployment` or `ReplicationController` depending on the provider(k8s/openshift).
