### ISSUE TITLE
`targetPort` is 0 in a converted service definition

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#60]
targetPort is 0 in a service

When doing the conversion, if a port is defined as "3306" it sets the service's `port` as `3306` but sets `targetPort` as `0`. This artifact works with k8s, when deployed, but the concern is of wrong/misleading info, generated. We can do a thing if a port is given as `X` set `X` as both `port` and `targetPort`. But if port given as `X:Y` we can set `targetPort` as `Y` and `port` as `X`.

I am using `docker-compose.yml` as:

```yaml
$ cat docker-compose.yml
version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: etherpad
      MYSQL_DATABASE: etherpad
      MYSQL_PASSWORD: etherpad
      MYSQL_USER: etherpad
```

convert:

```bash
$ ./kompose convert  -o output -y
file "output" created
```

wrong output

```yaml
$ cat output 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 0
  selector:
    service: mariadb
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mariadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: etherpad
        - name: MYSQL_DATABASE
          value: etherpad
        - name: MYSQL_PASSWORD
          value: etherpad
        - name: MYSQL_ROOT_PASSWORD
          value: etherpad
        image: centos/mariadb
        name: mariadb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
```

**Comment by surajssd** [comment]
One more example of wrong mapping, the following docker-compose file has port mapping as "80:9001" so `80` should be service's `port` field value and `9001` as `targetPort` here its doing exactly opposite.

docker-compose file
```yaml
$ cat docker-compose-two-ports.yml 
version: "2"

services:
  etherpad:
    build: "./myphp"
    ports:
      - "80:9001"
```

convert
```bash
$ ./kompose convert  -o output -y -f docker-compose-two-ports.yml 
file "output" created
```
output:

Observe here the value in service of `port` and `targetPort` are swapped. But in `deployment` the container definition has `containerPort` defined correctly.
```yaml
$ cat output 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: etherpad
  name: etherpad
spec:
  ports:
  - name: "9001"
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    service: etherpad
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      service: etherpad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: etherpad
    spec:
      containers:
      - name: etherpad
        ports:
        - containerPort: 9001
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
```
