### ISSUE TITLE
`--stdout` output as `List` kind

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#73]
When user applies `--stdout` as commandline arg then we can output all the objects as encapsulated in `kind: List`.

So this is what openshift with `oc import docker-compose` does
I believe we can use `metadata` in `List` to display warnings!

```yaml
apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
[SNIP]
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
[SNIP]
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
[SNIP]
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
[SNIP]
    selector:
      deploymentconfig: mariadb
  status:
    loadBalancer: {}
```
