### ISSUE TITLE
Wrong warning about networks

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#88]
wrong warning about networks not supported, even if networks not provided: `WARN[0000] Unsupported key networks - ignoring`

using `docker-compose.yml`
```yaml
$ cat docker-compose.yml 
version: "2"

services:
  redis:
    image: dharmit/redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - /opt/redis:/redis

  flask:
    image: dharmit/flask
    ports:
      - "31000:5000"
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
```

Output
```yaml
$ kompose convert --stdout -f docker-compose.yml -y
WARN[0000] Unsupported key depends_on - ignoring        
WARN[0000] Unsupported key networks - ignoring          
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
```
